    .catch((e) => {
        console.log(e); // "Error: Something went wrong"
    });